config/routes.rb
SimpleCms::Application.routes.draw do
   
  get "sessions/new"
    root :to => "sessions#new"
    match '/pracownicy/lista' => 'workers#lista', :as => :lista_pracownikow
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match 'wyszukiwanie/:id/raport' => 'searches#lista', :as => :raport_pracownicy_efektywnosc
    match '/szukaj/nowe', :controller => 'searches', :action => 'new', :as => 'nowe_szukanie'
    match '/szukaj/:id' => 'searches#show', :as => 'szukaj_po_id'

    get "rejestruj" => "users#new", :as => "rejestruj"
    get "zaloguj" => "sessions#new", :as => "zaloguj"
    post "wyloguj" => "sessions#destroy", :as => "wyloguj"
    
    match 'import' => 'workers#import_render', :as => 'import_danych'
    match 'pracownik/szczegoly/:id' => 'workers#szczegoly', :as => 'szczegoly_po_id'
    match 'pracownik/dodaj' => 'workers#new', :as => 'nowy_pracownik'
    match '/searches/nowe', :controller => 'searches', :action => 'new'
    match '/pracownicy' => 'workers#index', :as => :index
    match '/workers/wyszukaj/:id', :controller => 'workers', :action => 'wyszukaj' , :as => :info_pracownik
    match '/pomocnicze/nowa-predkosc' => 'pomocniczes#create' , :as => 'predkoscis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'dodatkis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'obszars'
    match '/tabela-normatywow/nowy-normatyw' => 'tabelanormatywows#create' , :as => 'tabelanormatywows'
    match '/tabela-transportowa/nowy-transport' => 'tabelatransportowas#create' , :as => 'tabelatransportowas'
    match '/tabela-czasow-dostepnych/nowy-czas' => 'tabelaczasowdostepnychs#create' , :as => 'tabelaczasowdostepnyches'
    match '/tabela-realizacji-norm/nowa-realizacja' => 'realizacjanorms#create' , :as => 'realizacjanorms'
    match '/pomocnicze' => 'pomocniczes#index' , :as => 'pomocnicze'
    match 'pracownicy/kalendarz' => 'workers#calendar' , :as => 'effectivenes_calendar'
    match 'efektywnosc/nowa' => 'effectivenes#create', :as => 'effectivenes_index'
    match 'tabela-normatywow' => 'tabelanormatywows#index', :as => 'tabela_normatywow'
    match 'tabela-transportowa' => 'tabelatransportowas#index', :as => 'tabela_transportowa'
    match 'typy-czynnosci' => 'typyczynnoscis#index', :as => 'typy_czynnosci'
    match 'tabela-czasow-dostepnych' => 'tabelaczasowdostepnychs#index', :as => 'tabela_czasow_dostepnych'
    match 'tabela-realizacji-norm' => 'realizacjanorms#index', :as => 'tabela_realizacji_norm'

    match 'obszar/edytuj/:id' => 'pomocniczes#edit_obszar', :as => 'edit_obszar'
    match 'obszar/update/:id' => 'pomocniczes#update_obszar', :as => 'obszar'
    match 'dodatek/edytuj/:id' => 'pomocniczes#edit_dodatek', :as => 'edit_dodatek'
    match 'dodatek/update/:id' => 'pomocniczes#update_dodatek', :as => 'dodatki'
    match 'predkosc/edytuj/:id' => 'pomocniczes#edit_predkosc', :as => 'edit_predkosc'
    match 'predkosc/update/:id' => 'pomocniczes#update_predkosc', :as => 'predkosci'

    match 'pracownik/usun/:id' => 'workers#delete', :as => 'usun_po_id'
    match 'typy-czynnosci/usun/:id' => 'typyczynnoscis#delete', :as => 'usun_po_id_czynnosc'
    match 'tabela-czynnosci/usun/:id' => 'tabelanormatywows#delete', :as => 'usun_po_id_normatyw'
    match 'tabela-transportowa/usun/:id' => 'tabelatransportowas#delete', :as => 'usun_po_id_transport'
    match 'tabela-czasow-dostepnych/usun/:id' => 'tabelaczasowdostepnychs#delete', :as => 'usun_po_id_czas_dostepny'
    match 'tabela-realizacji-norm/usun/:id' => 'realizacjanorms#delete', :as => 'usun_po_id_realizacja_norm'
    match 'pomocnicze/usun/:id' => 'pomocniczes#delete', :as => 'usun_po_id_predkosc'
    match 'pomocnicze/usun-dodatek/:id' => 'pomocniczes#delete_dodatek', :as => 'usun_po_id_dodatek'
    match 'pomocnicze/usun-obszar/:id' => 'pomocniczes#delete_obszar', :as => 'usun_po_id_obszar'
    match 'pracownik/:id2/cel/usun/:id' => 'celes#delete', :as => 'usun_po_id_cel'
    match 'pracownik/:id2/premia/usun/:id' => 'premies#delete', :as => 'usun_po_id_premia'
    match 'pracownik/:id2/efektywnosc/usun/:id' => 'effectivenes#delete', :as => 'usun_po_id_efektywnosc'
    match 'raporty/premie/usun/:id' => 'premies#delete', :as => 'usun_premia'
    match 'raporty/premie' => 'raporty#premie', :as => 'raport_premie'

    resources :typyczynnoscis do
      collection {get :index}
    end

    resources :searches
    resources :sessions
    resources :users
    resources :celes
    resources :premies
    resources :effectivenes
    resources :realizacjanorms
    resources :effectivene

    resources :tabelatransportowas

    
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/tabela-transportowa/export' => 'tabelatransportowas#export', :as => :export_tabela_transportowa
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match '/tabela-czasow-dostepnych/export' => 'tabelaczasowdostepnychs#export', :as => :export_czasy_dostepne
    match '/tabela-realizacji-norm/export' => 'realizacjanorms#export', :as => :export_realizacja_norm

    resources :workers do 
      collection {post :import , :import_tn, :import_tc, :import_tt,:import_tdc, :import_rn,:import_rn_finall,:import_workers,:import_stanowiska,:import_jednostki_organizacyjne}
    end

   match ':controller(/:action(/:id))(.:format)'
end

app/models/tabelaczasowdostepnych.rb
class Tabelaczasowdostepnych < ActiveRecord::Base

 self.table_name = 'tabela_czasow_dostepnych'
 validates_presence_of [:tcd_id_worker, 
                 :tcd_id_worker_merx, 
                 :tcd_data, 
                 :tcd_sum_godz_przep,
                 :tcd_sum_godz_chor], :on => :create


 attr_accessible :tcd_id_worker, 
                 :tcd_id_worker_merx, 
                 :tcd_data, 
                 :tcd_sum_godz_przep, 
                 :tcd_sum_godz_chor, 
            
                 :tcd_import_file_info,
                 :tcd_aud_us_id


def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Nieznany typ pliku: #{file.original_filename}"
  end
end
  def self.import(file)
  tcd_import_file_info = File.basename(file.original_filename, File.extname(file.original_filename))
  if Tabelaczasowdostepnych.all(:select => "tcd_import_file_info").to_a.to_s.include?(tcd_import_file_info) == false
      ex = open_spreadsheet(file)
      ex.default_sheet = 'CZAS_DOST'
      header = ['tcd_id_worker','tcd_id_worker_merx','tcd_data','tcd_sum_godz_przep','tcd_sum_godz_chor','tcd_import_file_info']
      (1..ex.last_row).each do |i|

      tcd_id_worker = ex.cell(i,'A')
      tcd_id_worker_merx = ex.cell(i,'B')
      tcd_data = ex.cell(i,'C')
      tcd_sum_godz_przep = ex.cell(i,'D')
      tcd_sum_godz_chor = ex.cell(i,'E')
     
      row = Hash[[header,[tcd_id_worker,tcd_id_worker_merx,tcd_data,tcd_sum_godz_przep,tcd_sum_godz_chor,tcd_import_file_info]].transpose]
      Tabelaczasowdostepnych.create row 
    end
  end
end



end            

app/controllers/tabelaczasowdostepnychs_controller.rb
class TabelaczasowdostepnychsController < ApplicationController
 

    filter_access_to :all

 layout 'worker'
before_filter :normatywy_all, :only => [:index,:export,:create]
before_filter :normatywy_by_id, :only => [:delete]

def normatywy_by_id
    @czas = Tabelaczasowdostepnych.find(params[:id])
 end
def normatywy_all
    @czasy = Tabelaczasowdostepnych.find(:all, order: "id desc")
end

def index
	@nowy_czas = Tabelaczasowdostepnych.new	
  respond_to do |format|
    format.html
    format.json { render json: CzasyDatatable.new(view_context) }
  end
end

def new
	@nowy_czas = Tabelaczasowdostepnych.new

end

def create
	@nowy_czas = Tabelaczasowdostepnych.new(params[:tabelaczasowdostepnych])	
	 if @nowy_czas.save 
    	redirect_to :action => "index"	
    	flash[:notice] = "Poprawnie dodano czas dostepny"
    else
    	flash[:notice] = "Nie udalo sie dodac czasu dostepnego sprawdz poprawnosc wypelnionych pol."
    	render "index"
    end
end

 def delete
    if @czas.destroy
      redirect_to :action => "index" 
      flash[:notice] = "Poprawnie usunieto normatyw z bazy"
    else
      redirect_to :action => "index" 
      flash[:notice] = "Nie udalo sie usunac normatywu"
    end
  end

def export
	respond_to do |format|
    	format.html
    	format.xls 	
	end
end

end

app/views/tabelaczasowdostepnychs/_czas.html.erb
<tr>

<td><%= czas.tcd_id_worker %></td>
<td><%= czas.tcd_id_worker_merx %></td>

<td style="width:100px;"><%= czas.tcd_data.strftime("%d-%m-%Y") %></td>
<td style="width:100px;"><%= czas.tcd_sum_godz_przep %> h</td>
<td style="width:100px;"><%= czas.tcd_sum_godz_przep - (((czas.tcd_sum_godz_przep)/8)*0.5).round(2)  %> h</td>
<!-- <td style="width:100px;"><%= czas.tcd_sum_godz_chor %></td> -->


<% if permitted_to? :delete, :tabelaczasowdostepnychs %>
        <td style="border:0;"><%= button_to("", usun_po_id_czas_dostepny_path(czas.id), :class=>"delete" ) %></td>
      <% end %>
</tr>

app/views/tabelaczasowdostepnychs/_form.html.erb
<table summary="Section form fields">
  <tr>
    <th><%= f.label :tcd_id_worker, "Id pracownika" %></th>
    <td><%= f.text_field :tcd_id_worker %></td>
   </tr><tr>

    <th><%= f.label :tcd_id_worker_merx, "Id pracownika merx" %></th>
    <td><%= f.text_field :tcd_id_worker_merx %></td>
  </tr>
  <tr>
    <th><%= f.label :tcd_data, "Data: " %></th>
    <td><%= f.text_field :tcd_data %></td>
  </tr><tr>
    <th><%= f.label :tcd_sum_godz_przep, "Suma godzin przepracowanych: " %></th>
    <td><%= f.text_field :tcd_sum_godz_przep, :placeholder => '0.0' %></td>
  </tr>
   <!-- <tr>
    <th><%= f.label :tcd_sum_godz_chor, "Suma godzin chorobowych: " %></th>
    <td><%= f.text_field :tcd_sum_godz_chor, :placeholder => '0.0' %></td>
   </tr>
 -->
   <tr>

    <th><%= f.label :tcd_import_file_info, "Źródło: " %></th>
    <td><%= f.text_field :tcd_import_file_info, :value => "Dodana ręcznie" %></td>
  </tr> 
 
    <%= f.hidden_field :tcd_aud_us_id, :value => current_user.id %>
   

</table>
     <%= submit_tag("" , :class => "add", :remote => true) %>

app/views/tabelaczasowdostepnychs/export.xls.erb
<% data = DateTime.now.to_date.strftime("%d-%m-%Y") %>
<% headers["Content-Disposition"] = "attachment; filename=\"tabela-czasow-dostepnych-#{data}.xls\""  %>
<table id="tczynnosci" border="1"class="listing" summary="Section list">
    <tr class="header">
      <th>Id pracownika </th>
      <th>Id pracownika merx</th>
    
      <th>Data</th>
      <th>Godziny przepracowane</th>
      <th>Godziny chorobowe</th>
    </tr>
    
 <% @czasy.each do |czas| %>
<tr>

<td><%= czas.tcd_id_worker %></td>
<td><%= czas.tcd_id_worker_merx %></td>

<td style="width:100px;"><%= czas.tcd_data.strftime("%d-%m-%Y") %></td>
<td style="width:100px;"><%= czas.tcd_sum_godz_przep %></td>
<td style="width:100px;"><%= czas.tcd_sum_godz_chor %></td>

</tr>
          
     <% end %>
   </table>
      

app/views/tabelaczasowdostepnychs/index.html.erb
<% title "Czasy dostępne" %>
 <div id="header" class="header-colored" style="background-color:rgb(233, 135, 29); ">
Tabela czasow dostępnych</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a><div id="visable-div" >


<div style="width:650px; float:left;">
<table id="tabela_czasow" class="dislpay" summary="Section list" data-source="<%= tabela_czasow_dostepnych_url(format: "json") %>" >
  <thead>
    <tr class="header">
      <th>Id pracownika </th>
      <th>Id pracownika merx</th>
    
      <th>Godziny przepracowane</th>
      <th>Godziny netto</th>
      <th>Data</th>
      <th>Źródło</th>
    </tr>
  </thead>
    
    <tbody>
    </tbody>
   </table>
      </div>
<div id="insert" style="float:right;margin-top:0px;margin-left:0px;">
  <p>Dodaj nowy czas:</p>

 <%= form_for @nowy_czas do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    
  <% end %>



    </div>  
 </div>