config/routes.rb
SimpleCms::Application.routes.draw do
   
  get "sessions/new"
    root :to => "sessions#new"
    match '/pracownicy/lista' => 'workers#lista', :as => :lista_pracownikow
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match 'wyszukiwanie/:id/raport' => 'searches#lista', :as => :raport_pracownicy_efektywnosc
    match '/szukaj/nowe', :controller => 'searches', :action => 'new', :as => 'nowe_szukanie'
    match '/szukaj/:id' => 'searches#show', :as => 'szukaj_po_id'

    get "rejestruj" => "users#new", :as => "rejestruj"
    get "zaloguj" => "sessions#new", :as => "zaloguj"
    post "wyloguj" => "sessions#destroy", :as => "wyloguj"
    
    match 'import' => 'workers#import_render', :as => 'import_danych'
    match 'pracownik/szczegoly/:id' => 'workers#szczegoly', :as => 'szczegoly_po_id'
    match 'pracownik/dodaj' => 'workers#new', :as => 'nowy_pracownik'
    match '/searches/nowe', :controller => 'searches', :action => 'new'
    match '/pracownicy' => 'workers#index', :as => :index
    match '/workers/wyszukaj/:id', :controller => 'workers', :action => 'wyszukaj' , :as => :info_pracownik
    match '/pomocnicze/nowa-predkosc' => 'pomocniczes#create' , :as => 'predkoscis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'dodatkis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'obszars'
    match '/tabela-normatywow/nowy-normatyw' => 'tabelanormatywows#create' , :as => 'tabelanormatywows'
    match '/tabela-transportowa/nowy-transport' => 'tabelatransportowas#create' , :as => 'tabelatransportowas'
    match '/tabela-czasow-dostepnych/nowy-czas' => 'tabelaczasowdostepnychs#create' , :as => 'tabelaczasowdostepnyches'
    match '/tabela-realizacji-norm/nowa-realizacja' => 'realizacjanorms#create' , :as => 'realizacjanorms'
    match '/pomocnicze' => 'pomocniczes#index' , :as => 'pomocnicze'
    match 'pracownicy/kalendarz' => 'workers#calendar' , :as => 'effectivenes_calendar'
    match 'efektywnosc/nowa' => 'effectivenes#create', :as => 'effectivenes_index'
    match 'tabela-normatywow' => 'tabelanormatywows#index', :as => 'tabela_normatywow'
    match 'tabela-transportowa' => 'tabelatransportowas#index', :as => 'tabela_transportowa'
    match 'typy-czynnosci' => 'typyczynnoscis#index', :as => 'typy_czynnosci'
    match 'tabela-czasow-dostepnych' => 'tabelaczasowdostepnychs#index', :as => 'tabela_czasow_dostepnych'
    match 'tabela-realizacji-norm' => 'realizacjanorms#index', :as => 'tabela_realizacji_norm'

    match 'obszar/edytuj/:id' => 'pomocniczes#edit_obszar', :as => 'edit_obszar'
    match 'obszar/update/:id' => 'pomocniczes#update_obszar', :as => 'obszar'
    match 'dodatek/edytuj/:id' => 'pomocniczes#edit_dodatek', :as => 'edit_dodatek'
    match 'dodatek/update/:id' => 'pomocniczes#update_dodatek', :as => 'dodatki'
    match 'predkosc/edytuj/:id' => 'pomocniczes#edit_predkosc', :as => 'edit_predkosc'
    match 'predkosc/update/:id' => 'pomocniczes#update_predkosc', :as => 'predkosci'

    match 'pracownik/usun/:id' => 'workers#delete', :as => 'usun_po_id'
    match 'typy-czynnosci/usun/:id' => 'typyczynnoscis#delete', :as => 'usun_po_id_czynnosc'
    match 'tabela-czynnosci/usun/:id' => 'tabelanormatywows#delete', :as => 'usun_po_id_normatyw'
    match 'tabela-transportowa/usun/:id' => 'tabelatransportowas#delete', :as => 'usun_po_id_transport'
    match 'tabela-czasow-dostepnych/usun/:id' => 'tabelaczasowdostepnychs#delete', :as => 'usun_po_id_czas_dostepny'
    match 'tabela-realizacji-norm/usun/:id' => 'realizacjanorms#delete', :as => 'usun_po_id_realizacja_norm'
    match 'pomocnicze/usun/:id' => 'pomocniczes#delete', :as => 'usun_po_id_predkosc'
    match 'pomocnicze/usun-dodatek/:id' => 'pomocniczes#delete_dodatek', :as => 'usun_po_id_dodatek'
    match 'pomocnicze/usun-obszar/:id' => 'pomocniczes#delete_obszar', :as => 'usun_po_id_obszar'
    match 'pracownik/:id2/cel/usun/:id' => 'celes#delete', :as => 'usun_po_id_cel'
    match 'pracownik/:id2/premia/usun/:id' => 'premies#delete', :as => 'usun_po_id_premia'
    match 'pracownik/:id2/efektywnosc/usun/:id' => 'effectivenes#delete', :as => 'usun_po_id_efektywnosc'
    match 'raporty/premie/usun/:id' => 'premies#delete', :as => 'usun_premia'
    match 'raporty/premie' => 'raporty#premie', :as => 'raport_premie'

    resources :typyczynnoscis do
      collection {get :index}
    end

    resources :searches
    resources :sessions
    resources :users
    resources :celes
    resources :premies
    resources :effectivenes
    resources :realizacjanorms
    resources :effectivene

    resources :tabelatransportowas

    
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/tabela-transportowa/export' => 'tabelatransportowas#export', :as => :export_tabela_transportowa
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match '/tabela-czasow-dostepnych/export' => 'tabelaczasowdostepnychs#export', :as => :export_czasy_dostepne
    match '/tabela-realizacji-norm/export' => 'realizacjanorms#export', :as => :export_realizacja_norm

    resources :workers do 
      collection {post :import , :import_tn, :import_tc, :import_tt,:import_tdc, :import_rn,:import_rn_finall,:import_workers,:import_stanowiska,:import_jednostki_organizacyjne}
    end

   match ':controller(/:action(/:id))(.:format)'
end

app/models/realizacjanorm.rb
class Realizacjanorm < ActiveRecord::Base
 belongs_to :worker

 self.table_name = 'realizacja_norm'
 validates_presence_of [:rn_id_worker_merx, 
                 :rn_data, 
                 :rn_magazyn, 
                 :rn_obszar,:rn_normatywy_czas_suma_tg
                 # ,:rn_normatywy_czas_suma_tj
                 ], :on => :create


 attr_accessible :rn_id_worker,
                 :rn_id_worker_hr,
                 :rn_id_worker_merx,
                 :rn_data,
    
                 :rn_obszar,
                 :rn_magazyn,
                 :rn_typ_operacji,
                 :rn_komentarz,

                 :rn_normatywy_czas_suma_tg,
                 :rn_normatywy_czas_suma_tj,
                
                 :rn_import_file_info,
                 :rn_aud_us_id
    
 



def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Nieznany typ pliku: #{file.original_filename}"
  end
end
def self.import(file)
  rn_import_file_info = File.basename(file.original_filename, File.extname(file.original_filename))
  if Realizacjanorm.all(:select => "rn_import_file_info").to_a.to_s.include?(rn_import_file_info) == false
      ex = open_spreadsheet(file)
      ex.default_sheet = 'REALIZACJA_NORM'
      header = ['rn_id_worker','rn_id_worker_hr','rn_id_worker_merx','rn_data','rn_obszar',
                'rn_magazyn','rn_typ_operacji','rn_komentarz',
                'rn_normatywy_czas_suma_tg','rn_normatywy_czas_suma_tj',
                'rn_import_file_info']
      (4..ex.last_row).each do |i|

      rn_id_worker = ex.cell(i,'A')
      rn_id_worker_hr = ex.cell(i,'B')
      rn_id_worker_merx = ex.cell(i,'C')
      rn_data = ex.cell(i,'D')
      rn_obszar = ex.cell(i,'E')
      rn_magazyn = ex.cell(i,'F')
      rn_typ_operacji = ex.cell(i,'G')
      rn_komentarz = ex.cell(i,'H')
      rn_normatywy_czas_suma_tg = ex.cell(i,'I')
      rn_normatywy_czas_suma_tj = ex.cell(i,'J')
   

      row = Hash[[header,[rn_id_worker,rn_id_worker_hr,rn_id_worker_merx,rn_data,rn_obszar,
                          rn_magazyn,rn_typ_operacji, rn_komentarz,
                          rn_normatywy_czas_suma_tg, rn_normatywy_czas_suma_tj, 
                          rn_import_file_info]].transpose]
      Realizacjanorm.create row 
    end
  end
end

def self.import_finall(file)
  rn_import_file_info = File.basename(file.original_filename, File.extname(file.original_filename))
  if Realizacjanorm.all(:select => "rn_import_file_info").to_a.to_s.include?(rn_import_file_info) == false
      ex = open_spreadsheet(file)
      ex.default_sheet = 'USER'
      header = [
        # 'rn_id_worker',
        #'rn_id_worker_hr',
         'rn_id_worker_merx',
        'rn_data',
        'rn_obszar',
                'rn_magazyn',
                'rn_typ_operacji',
                # 'rn_komentarz',
                'rn_normatywy_czas_suma_tg',
                 'rn_normatywy_czas_suma_tj',
                'rn_import_file_info']
      (4..ex.last_row).each do |i|

      rn_id_worker_merx = ex.cell(i,'B')
      
      rn_data = ex.cell(i,'J')
      rn_obszar = ex.cell(i,'F')
      rn_magazyn = ex.cell(i,'D')
      rn_typ_operacji = ex.cell(i,'N')
      # rn_komentarz = ex.cell(i,'H')
      rn_normatywy_czas_suma_tg = ex.cell(i,'BQ')
      dodatek_na_obszar = Obszar.where("ob_kod =? ", rn_obszar).order('created_at desc').limit(1).pluck(:ob_wartosc)
      rn_normatywy_czas_suma_tj = (rn_normatywy_czas_suma_tg * (100 +  dodatek_na_obszar[0].to_f )/100).round(2)
   

      row = Hash[[header,[
                        # rn_id_worker,
                        # rn_id_worker_hr,
                         rn_id_worker_merx,
                          rn_data,
                          rn_obszar,
                          rn_magazyn,
                          rn_typ_operacji, 
                          # rn_komentarz,
                          rn_normatywy_czas_suma_tg, 
                           rn_normatywy_czas_suma_tj, 
                          rn_import_file_info]].transpose]
      Realizacjanorm.create row 
    end
  end
end


end

app/controllers/realizacjanorms_controller.rb
class RealizacjanormsController < ApplicationController
 

    filter_access_to :all

layout 'worker'
before_filter :normatywy_all, :only => [:index,:export,:create]
before_filter :normatywy_by_id, :only => [:delete]

def normatywy_by_id
    @norma = Realizacjanorm.find(params[:id])
 end
def normatywy_all
     # @normy = Realizacjanorm.find(:all, :order => "rn_data desc", :limit => 1000, :conditions => "rn_normatywy_czas_suma_tg >= 0")
end

def index

	@nowa_norma = Realizacjanorm.new	
  respond_to do |format|
    format.html
    format.json { render json: NormsDatatable.new(view_context) }
  end
end

def new
	@nowa_norma = Realizacjanorm.new	
end

def create
	@nowa_norma = Realizacjanorm.new(params[:realizacjanorm])	
	 if @nowa_norma.save 
    	redirect_to :action => "index"	
    	flash[:notice] = "Poprawnie dodano normatyw"
    else
    	flash[:notice] = "Nie udalo sie dodac normatywu sprawdz poprawnosc wypelnionych pol."
    	render "index"
    end
end

 def delete
    if @norma.destroy
      redirect_to :action => "index" 
      flash[:notice] = "Poprawnie usunieto normatyw z bazy"
    else
      redirect_to :action => "index" 
      flash[:notice] = "Nie udalo sie usunac normatywu"
    end
  end

def export


	respond_to do |format|
    	format.html 
    	format.xls 	
	end
end

end

app/views/realizacjanorms/_form.html.erb
<table id="ttrans" summary="Section form fields">
  <tr>
    <th><%= f.label :rn_id_worker, "Id pracownika" %></th>
    <td style="width:60px;"><%= f.text_field :rn_id_worker, :style=> 'width:60px;' %></td>
    <th><%= f.label :rn_data, "Data: " %></th>
    <td ><%= f.text_field :rn_data %></td>
   
  
  </tr>
  <tr>
 <th><%= f.label :rn_id_worker_merx, "Id pracownika merx" %></th>
    <td style="width:60px;"><%= f.text_field :rn_id_worker_merx,  :style=>"width:60px;" %></td>   

    <th><%= f.label :rn_magazyn, "Magazyn: " %></th>
    <td><%= f.text_field :rn_magazyn %></td>

    
  </tr> 
  <tr>
    <th><%= f.label :rn_obszar, "Obszar: " %></th>
    <td><%= f.collection_select :rn_obszar, Obszar.find(:all), :id, :ob_kod, :prompt => "Wybierz obszar" %></td>
   
    <th><%= f.label :rn_typ_operacji, "Typ operacji: " %></th>
      <td><%= f.select(:rn_typ_operacji, options_for_select([
      ['kompletacja', 'kompletacja'], 
      ['rozładunek', 'rozładunek'], 
      ['przesunięcie', 'przesunięcie'], 
      ['załadunek', 'załadunek'], 
      ['przyjęcie', 'przyjęcie'], 
      ['rozwożenie', 'rozwożenie']],
      1) , :prompt => "Wybierz operacje") %>
    </td>

  </tr>

   <tr>
  
  </tr><tr>
    <th><%= f.label :rn_normatywy_czas_suma_tg, "Suma godzin przepracowanych [tg]: " %></th>
    <td style="width:60px;"><%= f.text_field :rn_normatywy_czas_suma_tg, :placeholder => '0.0',  :style=>"width:60px;" %></td>
   <th><%= f.label :rn_komentarz, "Komentarz:  " %></th>
    <td colspan="4"><%= f.text_area :rn_komentarz , :size => "50x5", :placeholder => "maksymalnie 255 znaków"%></td>
    <!-- <th><%= f.label :rn_normatywy_czas_suma_tj, "Suma godzin  przepracowanych [tj]: " %></th>
    <td><%= f.text_field :rn_normatywy_czas_suma_tj, :placeholder => '0.0' %></td> -->
  </tr>

 
    <%= f.hidden_field :rn_aud_us_id, :value => current_user.id %>
   

</table>
     <%= submit_tag("" , :class => "add", :remote => true) %>

app/views/realizacjanorms/_norma.html.erb
<tr>

<td > <%= norma.rn_id_worker %> </td>
<td > <%= norma.rn_id_worker_merx %> </td>

<td style="width:80px"> <%= norma.rn_data.strftime("%d-%m-%Y") %> </td>

<td style="width:60px"> <%= norma.rn_obszar %> </td>
<td style="width:60px"> <%= norma.rn_magazyn %> </td>
<td style="width:60px"> <%= norma.rn_typ_operacji %> </td>


<td style="width:100px"> <%= norma.rn_normatywy_czas_suma_tg  %> </td>
<td style="width:100px"> <%= (norma.rn_normatywy_czas_suma_tg * (100 +  dodatek_by_obszar(norma.rn_obszar)[0].to_f )/100).round(2) %> </td>
<!-- <td style="width:100px"> <%= norma.rn_tabela_transportowa_suma_tg %> </td>
<td style="width:100px"> <%= norma.rn_tabela_transportowa_suma_tj %> </td> -->
<td> <%= norma.rn_suma_tj %> </td>

<td> <%= norma.rn_import_file_info %> </td>
<td> <%= norma.rn_komentarz %> </td>
<!-- 
<% if permitted_to? :delete, :realizacjanorms %>
        <td style="border:0;"><%= button_to("", usun_po_id_realizacja_norm_path(norma.id), :class=>"delete" ) %></td>
      <% end %> -->
</tr>

app/views/realizacjanorms/export.xls.erb
<% data = DateTime.now.to_date.strftime("%d-%m-%Y") %>
<% headers["Content-Disposition"] = "attachment; filename=\"tabela-realizacji-norm-#{data}.xls\""  %>

<table id="normy" class="display" style="font-size:12px; width:100%;" data-source="<%= tabela_realizacji_norm_url(format: "json") %>" summary="Section list">
  <thead>
    <tr style="text-align:left;">
      <th>ID HR</th>
      <th>Id HR Merx</th>
    
      <th>Data realizacji</th>
      <th>Obszar</th>
      <th>Magazyn</th>
      <th>Typ operacji</th>
   
      <th>Czas normatywu [TG]</th>
      <th>Czas normatywu [TJ]</th>
    <!--   <th>Czas tabela-transportowa [tg]</th>
      <th>Czas tabela-transportowa [tj]</th> -->
      <!-- <th>Suma czasów [tj]</th> -->

      <th>Komentarz</th>
    </tr>
    </thead>
    <tbody>

   </tbody>
   </table>

app/views/realizacjanorms/index.html.erb
<% title "Realizacja norm" %>
<div id="header" class="header-colored" style="background-color:rgb(233, 135, 29); ">
Dodawanie nowej realizacji
</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a><div id="visable-div" >


<div id="insert" style="width:80%;float:left;margin:0;padding:0 10px 10px 0;">
  <p>Dodaj nowy czas:</p>

 <%= form_for @nowa_norma do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    
  <% end %>




 </div> 
<%= button_to "" , export_realizacja_norm_path(format: "xls"), :class => "export-excel", :style => "margin:0 0 0 20px;" %>

 </div> 


<div id="header" class="header-colored" style="background-color:rgb(233, 35, 29); ">
Tabela realizacji norm
</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a><div id="visable-div" >



<table id="normy" class="display" style="font-size:12px; width:100%;" data-source="<%= tabela_realizacji_norm_url(format: "json") %>" summary="Section list">
  <thead>
    <tr style="text-align:left;">
      <th>ID Pracownika</th>
      <th>Id HR </th>
      <th>Id HR Merx</th>
    
      <th>Data realizacji</th>
      <th>Obszar</th>
      <th>Magazyn</th>
      <th>Typ operacji</th>
   
      <th>Czas normatywu [TG]</th>
      <th>Czas normatywu [TJ]</th>
    <!--   <th>Czas tabela-transportowa [tg]</th>
      <th>Czas tabela-transportowa [tj]</th> -->
      <!-- <th>Suma czasów [tj]</th> -->

      <th>Komentarz</th>
    </tr>
    </thead>
    <tbody>

   </tbody>
   </table>


</div>
</div>
   