config/routes.rb
SimpleCms::Application.routes.draw do
   
  get "sessions/new"
    root :to => "sessions#new"
    match '/pracownicy/lista' => 'workers#lista', :as => :lista_pracownikow
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match 'wyszukiwanie/:id/raport' => 'searches#lista', :as => :raport_pracownicy_efektywnosc
    match '/szukaj/nowe', :controller => 'searches', :action => 'new', :as => 'nowe_szukanie'
    match '/szukaj/:id' => 'searches#show', :as => 'szukaj_po_id'

    get "rejestruj" => "users#new", :as => "rejestruj"
    get "zaloguj" => "sessions#new", :as => "zaloguj"
    post "wyloguj" => "sessions#destroy", :as => "wyloguj"
    
    match 'import' => 'workers#import_render', :as => 'import_danych'
    match 'pracownik/szczegoly/:id' => 'workers#szczegoly', :as => 'szczegoly_po_id'
    match 'pracownik/dodaj' => 'workers#new', :as => 'nowy_pracownik'
    match '/searches/nowe', :controller => 'searches', :action => 'new'
    match '/pracownicy' => 'workers#index', :as => :index
    match '/workers/wyszukaj/:id', :controller => 'workers', :action => 'wyszukaj' , :as => :info_pracownik
    match '/pomocnicze/nowa-predkosc' => 'pomocniczes#create' , :as => 'predkoscis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'dodatkis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'obszars'
    match '/tabela-normatywow/nowy-normatyw' => 'tabelanormatywows#create' , :as => 'tabelanormatywows'
    match '/tabela-transportowa/nowy-transport' => 'tabelatransportowas#create' , :as => 'tabelatransportowas'
    match '/tabela-czasow-dostepnych/nowy-czas' => 'tabelaczasowdostepnychs#create' , :as => 'tabelaczasowdostepnyches'
    match '/tabela-realizacji-norm/nowa-realizacja' => 'realizacjanorms#create' , :as => 'realizacjanorms'
    match '/pomocnicze' => 'pomocniczes#index' , :as => 'pomocnicze'
    match 'pracownicy/kalendarz' => 'workers#calendar' , :as => 'effectivenes_calendar'
    match 'efektywnosc/nowa' => 'effectivenes#create', :as => 'effectivenes_index'
    match 'tabela-normatywow' => 'tabelanormatywows#index', :as => 'tabela_normatywow'
    match 'tabela-transportowa' => 'tabelatransportowas#index', :as => 'tabela_transportowa'
    match 'typy-czynnosci' => 'typyczynnoscis#index', :as => 'typy_czynnosci'
    match 'tabela-czasow-dostepnych' => 'tabelaczasowdostepnychs#index', :as => 'tabela_czasow_dostepnych'
    match 'tabela-realizacji-norm' => 'realizacjanorms#index', :as => 'tabela_realizacji_norm'

    match 'obszar/edytuj/:id' => 'pomocniczes#edit_obszar', :as => 'edit_obszar'
    match 'obszar/update/:id' => 'pomocniczes#update_obszar', :as => 'obszar'
    match 'dodatek/edytuj/:id' => 'pomocniczes#edit_dodatek', :as => 'edit_dodatek'
    match 'dodatek/update/:id' => 'pomocniczes#update_dodatek', :as => 'dodatki'
    match 'predkosc/edytuj/:id' => 'pomocniczes#edit_predkosc', :as => 'edit_predkosc'
    match 'predkosc/update/:id' => 'pomocniczes#update_predkosc', :as => 'predkosci'

    match 'pracownik/usun/:id' => 'workers#delete', :as => 'usun_po_id'
    match 'typy-czynnosci/usun/:id' => 'typyczynnoscis#delete', :as => 'usun_po_id_czynnosc'
    match 'tabela-czynnosci/usun/:id' => 'tabelanormatywows#delete', :as => 'usun_po_id_normatyw'
    match 'tabela-transportowa/usun/:id' => 'tabelatransportowas#delete', :as => 'usun_po_id_transport'
    match 'tabela-czasow-dostepnych/usun/:id' => 'tabelaczasowdostepnychs#delete', :as => 'usun_po_id_czas_dostepny'
    match 'tabela-realizacji-norm/usun/:id' => 'realizacjanorms#delete', :as => 'usun_po_id_realizacja_norm'
    match 'pomocnicze/usun/:id' => 'pomocniczes#delete', :as => 'usun_po_id_predkosc'
    match 'pomocnicze/usun-dodatek/:id' => 'pomocniczes#delete_dodatek', :as => 'usun_po_id_dodatek'
    match 'pomocnicze/usun-obszar/:id' => 'pomocniczes#delete_obszar', :as => 'usun_po_id_obszar'
    match 'pracownik/:id2/cel/usun/:id' => 'celes#delete', :as => 'usun_po_id_cel'
    match 'pracownik/:id2/premia/usun/:id' => 'premies#delete', :as => 'usun_po_id_premia'
    match 'pracownik/:id2/efektywnosc/usun/:id' => 'effectivenes#delete', :as => 'usun_po_id_efektywnosc'
    match 'raporty/premie/usun/:id' => 'premies#delete', :as => 'usun_premia'
    match 'raporty/premie' => 'raporty#premie', :as => 'raport_premie'

    resources :typyczynnoscis do
      collection {get :index}
    end

    resources :searches
    resources :sessions
    resources :users
    resources :celes
    resources :premies
    resources :effectivenes
    resources :realizacjanorms
    resources :effectivene

    resources :tabelatransportowas

    
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/tabela-transportowa/export' => 'tabelatransportowas#export', :as => :export_tabela_transportowa
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match '/tabela-czasow-dostepnych/export' => 'tabelaczasowdostepnychs#export', :as => :export_czasy_dostepne
    match '/tabela-realizacji-norm/export' => 'realizacjanorms#export', :as => :export_realizacja_norm

    resources :workers do 
      collection {post :import , :import_tn, :import_tc, :import_tt,:import_tdc, :import_rn,:import_rn_finall,:import_workers,:import_stanowiska,:import_jednostki_organizacyjne}
    end

   match ':controller(/:action(/:id))(.:format)'
end

app/models/tabelatransportowa.rb
class Tabelatransportowa < ActiveRecord::Base

self.table_name = 'tabela_transportowa'
 # validates_presence_of [:tn_kod_czynnosci, 
 #                 :tn_obszar, 
 #                 :tn_opis_czynnosci, 
 #                 :tn_jednostka_odniesienia, 
 #                 :tn_czas,
 #                 :tn_import_file_info], :on => :create

has_one :dodatek
has_one :predkosc
 attr_accessible :tt_id, 
                  :tt_nr_drogi,
                  :tt_nr_drogi_system,
                  :tt_przebieg_trasy,
                  :tt_opis_trasy,
                  :tt_typ_operacji,
                  :tt_obszar,
                  :tt_ruch_od,
                  :tt_ruch_do,
                  :tt_srodek_transportu,
                  :tt_dystans_od,
                  :tt_dystans_do,
                  :tt_ilosc_zakretow,
                  :tt_ilosc_start_stop,
                  :tt_rodzaj_pobrania,
                  :tt_komentarz,
                  :tt_predkosc_kod,
                  :tt_dodatek_kod,
                  :tt_import_file_info,
                  :tt_aud_us_id
    
 def self.to_csv (options = {})
   CSV.generate(options) do |csv|
     csv << column_names
     all.each do |tt|
       csv << tt.attributes.values_at(*column_names)
     end
   end
  
 end



def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Nieznany typ pliku: #{file.original_filename}"
  end
end
  def self.import(file)
  tt_import_file_info = File.basename(file.original_filename, File.extname(file.original_filename))
  if Tabelatransportowa.all(:select => "tt_import_file_info").to_a.to_s.include?(tt_import_file_info) == false
      ex = open_spreadsheet(file)
      ex.default_sheet = 'TABELA_TRANSPORTOWA'
      header = ['tt_nr_drogi',
                'tt_nr_drogi_system',
                'tt_przebieg_trasy',
                'tt_opis_trasy',
                'tt_typ_operacji',
                'tt_obszar',
                'tt_ruch_od',
                'tt_ruch_do',
                'tt_srodek_transportu',
                'tt_dystans_od',
                'tt_dystans_do',
                'tt_ilosc_zakretow',
                'tt_ilosc_start_stop',
                'tt_rodzaj_pobrania',
                'tt_komentarz',
                'tt_predkosc_kod',
                'tt_dodatek_kod',
                'tt_import_file_info']
      (5..ex.last_row).each do |i|

      tt_nr_drogi = ex.cell(i,'A')
      tt_nr_drogi_system = ex.cell(i,'B')
      tt_przebieg_trasy = ex.cell(i,'C')
      tt_opis_trasy = ex.cell(i,'D')
      tt_typ_operacji = ex.cell(i,'E')
      tt_obszar = ex.cell(i,'F')
      tt_ruch_od = ex.cell(i,'G')
      tt_ruch_do = ex.cell(i,'H')
      tt_srodek_transportu = ex.cell(i,'I')
      tt_dystans_od = ex.cell(i,'J')
      tt_dystans_do = ex.cell(i,'K')
      tt_ilosc_zakretow = ex.cell(i,'L')
      tt_ilosc_start_stop = ex.cell(i,'M')
      tt_rodzaj_pobrania = ex.cell(i,'N')
      tt_komentarz = ex.cell(i,'O')
      tt_predkosc_kod = ex.cell(i,'P')
      tt_dodatek_kod = ex.cell(i,'Q')
      row = Hash[[header,[tt_nr_drogi,
                          tt_nr_drogi_system,
                          tt_przebieg_trasy,
                          tt_opis_trasy,
                          tt_typ_operacji,
                          tt_obszar,
                          tt_ruch_od,
                          tt_ruch_do,
                          tt_srodek_transportu,
                          tt_dystans_od,
                          tt_dystans_do,
                          tt_ilosc_zakretow,
                          tt_ilosc_start_stop,
                          tt_rodzaj_pobrania,
                          tt_komentarz,
                          tt_predkosc_kod,
                          tt_dodatek_kod,
                          tt_import_file_info]].transpose]
      Tabelatransportowa.create row 
    end
  end
end


end

app/controllers/tabelatransportowas_controller.rb
class TabelatransportowasController < ApplicationController
 

    filter_access_to :all

 layout 'worker'
before_filter :normatywy_all, :only => [:index,:export,:create]
before_filter :normatywy_by_id, :only => [:delete]

def normatywy_by_id
    @transport = Tabelatransportowa.find(params[:id])
 end
def normatywy_all
   # @transporty = Tabelatransportowa.find(:all, order: "id desc")
end

def index
	@nowy_transport = Tabelatransportowa.new	
  respond_to do |format|
  format.html
  format.json { render json: TabelaTransportowaDatatable.new(view_context) }
  end
end

def new
	@nowy_transport = Tabelatransportowa.new
  

end

def create
	@nowy_transport = Tabelatransportowa.new(params[:tabelatransportowa])	
	 if @nowy_transport.save 
    	redirect_to :action => "index"	
    	flash[:notice] = "Poprawnie dodano transport"
    else
    	flash[:notice] = "Nie udalo sie dodac transportu sprawdz poprawnosc wypelnionych pol."
    	render "index"
    end
end

 def delete
    if @transport.destroy
      redirect_to :action => "index" 
      flash[:notice] = "Poprawnie usunieto normatyw z bazy"
    else
      redirect_to :action => "index" 
      flash[:notice] = "Nie udalo sie usunac normatywu"
    end
  end

def export
	respond_to do |format|
    	format.html
    	format.xls 	
	end
end

end

app/views/tabelatransportowas/_form.html.erb
<table id="ttrans" summary="Section form fields">
  <tr>
    <th><%= f.label :tt_nr_drogi, "Numer drogi: " %></th>
    <td><%= f.text_field :tt_nr_drogi %></td>
    <th><%= f.label :tt_nr_drogi_system, "Numer drogi z systemu: " %></th>
    <td><%= f.text_field :tt_nr_drogi_system %></td>
  </tr>
  <tr>
    <th><%= f.label :tt_przebieg_trasy, "Przebieg trasy: " %></th>
    <td><%= f.text_field :tt_przebieg_trasy %></td>
  
    <th><%= f.label :tt_opis_trasy, "Opis trasy: " %></th>
    <td><%= f.text_field :tt_opis_trasy %></td>
  </tr>
   <tr>
    <th><%= f.label :tt_typ_operacji, "Typ operacji: " %></th>
    <td><%= f.select(:tt_typ_operacji, options_for_select([
      ['kompletacja', 'kompletacja'], 
      ['rozładunek', 'rozładunek'], 
      ['przesunięcie', 'przesunięcie'], 
      ['załadunek', 'załadunek'], 
      ['przyjęcie', 'przyjęcie'], 
      ['rozwożenie', 'rozwożenie']],
      1) ) %>
    </td>
  </tr>
  <tr>
    <th><%= f.label :tt_obszar, "Obszar: " %></th>
    <td><%= f.text_field :tt_obszar %></td>
  
    <th><%= f.label :tt_ruch_od, "Ruch z: " %></th>
    <td><%= f.text_field :tt_ruch_od %></td>
  
    <th><%= f.label :tt_ruch_do, "Ruch do: " %></th>
    <td><%= f.text_field :tt_ruch_do %></td>
  </tr> 
  <tr>
    <th><%= f.label :tt_srodek_transportu, "Środek transportu: " %></th>
     <td><%= f.select(:tt_srodek_transportu, options_for_select([
      ['czołowy', 'czołowy'], 
      ['systemowy', 'systemowy'], 
      ['retrak', 'retrak'], 
      ['ręczny', 'ręczny'], 
      ['piesek', 'piesek'], 
      ['paleciak', 'paleciak'], 
      ['transportowy', 'transportowy'], 
      ['ciągnik', 'ciągnik'], 
      ['pieszo', 'pieszo']], 
      
      1) ) %></td>
  </tr>
   
    <tr>
    <th><%= f.label :tt_dystans_od, "Dystans od: " %></th>
    <td><%= f.text_field :tt_dystans_od, :placeholder => '0.0'  %></td>
 
    <th><%= f.label :tt_dystans_do, "Dystans do: " %></th>
    <td><%= f.text_field :tt_dystans_do, :placeholder => '0.0'  %></td>
  </tr>
   <tr>
    <th><%= f.label :tt_ilosc_zakretow, "Ilość zakrętów: " %></th>
    <td><%= f.text_field :tt_ilosc_zakretow %></td>
  
    <th><%= f.label :tt_ilosc_start_stop, "Ilość start/stop: " %></th>
    <td><%= f.text_field :tt_ilosc_start_stop %></td>
  </tr>
   <tr>
    <th><%= f.label :tt_rodzaj_pobrania, "Rodzaj pobrania: " %></th>
    <td><%= f.text_field :tt_rodzaj_pobrania %></td>
  
    <th><%= f.label :tt_komentarz, "Komentarz: " %></th>
    <td><%= f.text_field :tt_komentarz %></td>
  </tr>
   <tr>
    <th><%= f.label :tt_predkosc_kod, "Kod prędkości: " %></th>
    <td><%= f.select(:tt_predkosc_kod, options_for_select([
      ['F-MAX', 'F-MAX'], 
      ['F-ŚREDNIA', 'F-ŚREDNIA'], 
      ['F-PEŁZANIA', 'F-PEŁZANIA'], 
      ['P-MAX', 'P-MAX'], 
      ['P-MIN', 'P-MIN'], 
      ['KA', 'KA']],
      1) ) %>
    </td>
  </tr>

    <%= f.hidden_field :tt_import_file_info, :value => "Wpisana ręcznie" %>
    
    <%= f.hidden_field :tt_aud_us_id, :value => current_user.id %>
   


</table>
     <%= submit_tag("" , :class => "add", :remote => true) %>

app/views/tabelatransportowas/export.xls.erb
<% data = DateTime.now.to_date.strftime("%d-%m-%Y") %>
<% headers["Content-Disposition"] = "attachment; filename=\"tabela-transportowa-#{data}.xls\""  %>

<table border="1">
    <border="1"class="listing" summary="Section list">
    <tr class="header">
      <th>Nr.<br/>drogi</th>
      <th>Nr.<br/>z systemu</th>
      <th>Przebieg trasy</th>
      <th>Opis trasy</th>
      <th>Typ<br/>operacji</th>
      <th>Obszar</th>
      <th>Ruch od</th>
      <th>Ruch do</th>
      <th>Środek<br/>transporu</th>
      <th>Dystans od</th>
      <th>Dystans do</th>
      <th>Ilość zakrętów</th>
      <th>Ilość start/stop</th>
      <th>Rodzaj pobrania</th>
      <th>Komentarz</th>
      <th>Kod prędkości</th>
      <th>Pochodzenie</th>
      <th>Data dodania</th>
     
    </tr>
 <% @transporty.each do |transport| %>
 <tr >

      <td><%= transport.tt_nr_drogi %></td>
      <td><%= transport.tt_nr_drogi_system %></td>
      <td><%= transport.tt_przebieg_trasy %></td>
      <td><%= transport.tt_opis_trasy %></td>
      <td><%= transport.tt_typ_operacji %></td>
      <td><%= transport.tt_obszar %></td>
      <td><%= transport.tt_ruch_od %></td>
      <td><%= transport.tt_ruch_do %></td>
      <td><%= transport.tt_srodek_transportu %></td>
      <td><%= transport.tt_dystans_od.to_f.round(2) %></td>
      <td><%= transport.tt_dystans_do.to_f.round(2) %></td>
      <td><%= transport.tt_ilosc_zakretow %></td>
      <td><%= transport.tt_ilosc_start_stop %></td>
      <td><%= transport.tt_rodzaj_pobrania %></td>
      <td><%= transport.tt_komentarz %></td>
      <td><%= transport.tt_predkosc_kod %></td>
      <td><%= transport.tt_import_file_info %>
      <td><%= transport.created_at.strftime("%d-%m-%Y") %>
      <% if permitted_to? :delete, :tabelatransportowas %>
        <td><%= button_to("usuń", usun_po_id_transport_path(transport.id), :class=>"szczegoly" ) %></td>
      <% end %>
      </tr>
          
     <% end %>




   </table>

app/views/tabelatransportowas/index.html.erb
<% title "Tabela Transportowa" %>
<div id="header" class="header-colored" style="background-color:rgb(233, 135, 29); ">
Dodawanie nowego transportu
</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a>
<div id="visable-div" >
<div id="insert" style="margin-top:0; padding:10px;">

 <%= form_for @nowy_transport do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    
  <% end %>
</div>
</div>
<div id="header" class="header-colored" style="background-color:rgb(33, 135, 129); ">
Tabela transportowa
</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a><div id="visable-div" >

<div id="tabela-div">
  
<table id="tabela_transportowa" class="display" style="font-size:12px;" summary="Section list" data-source="<%= tabela_transportowa_url(format: "json") %>">
     <thead>
    <tr style="text-align:left;" >
      <th>Nr. drogi</th>
      <th>Nr. z systemu</th>
      <th>Przebieg trasy</th>
      <th>Opis trasy</th>
      <th>Typ operacji</th>
      <th>Obszar</th>
      <th>Ruch od</th>
      <th>Ruch do</th>
      <th>Środek transporu</th>
      <th>Dystans od</th>
      <th>Dystans do</th>
      <th>Ilość zakrętów</th>
      <th>Ilość start/stop</th>
      <th>Rodzaj pobrania</th>
      <th>Kod prędkości</th>
      <th>Kod dodatku pobranie i umieszczenie</th>
      <th>Czas przejazdu bez pobrania i umiesczenia [sek/1kurs]</th>
      <th>Komentarz</th>
      <!-- <th>Data dodania</th> -->
      <!-- <th>Pochodzenie</th> -->
    </tr>
    </thead>
      <tbody>

      </tbody>

   </table>
</div>
</div>
</div>