config/routes.rb
SimpleCms::Application.routes.draw do
   
  get "sessions/new"
    root :to => "sessions#new"
    match '/pracownicy/lista' => 'workers#lista', :as => :lista_pracownikow
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match 'wyszukiwanie/:id/raport' => 'searches#lista', :as => :raport_pracownicy_efektywnosc
    match '/szukaj/nowe', :controller => 'searches', :action => 'new', :as => 'nowe_szukanie'
    match '/szukaj/:id' => 'searches#show', :as => 'szukaj_po_id'

    get "rejestruj" => "users#new", :as => "rejestruj"
    get "zaloguj" => "sessions#new", :as => "zaloguj"
    post "wyloguj" => "sessions#destroy", :as => "wyloguj"
    
    match 'import' => 'workers#import_render', :as => 'import_danych'
    match 'pracownik/szczegoly/:id' => 'workers#szczegoly', :as => 'szczegoly_po_id'
    match 'pracownik/dodaj' => 'workers#new', :as => 'nowy_pracownik'
    match '/searches/nowe', :controller => 'searches', :action => 'new'
    match '/pracownicy' => 'workers#index', :as => :index
    match '/workers/wyszukaj/:id', :controller => 'workers', :action => 'wyszukaj' , :as => :info_pracownik
    match '/pomocnicze/nowa-predkosc' => 'pomocniczes#create' , :as => 'predkoscis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'dodatkis'
    match '/pomocnicze/nowy-dodatek' => 'pomocniczes#create' , :as => 'obszars'
    match '/tabela-normatywow/nowy-normatyw' => 'tabelanormatywows#create' , :as => 'tabelanormatywows'
    match '/tabela-transportowa/nowy-transport' => 'tabelatransportowas#create' , :as => 'tabelatransportowas'
    match '/tabela-czasow-dostepnych/nowy-czas' => 'tabelaczasowdostepnychs#create' , :as => 'tabelaczasowdostepnyches'
    match '/tabela-realizacji-norm/nowa-realizacja' => 'realizacjanorms#create' , :as => 'realizacjanorms'
    match '/pomocnicze' => 'pomocniczes#index' , :as => 'pomocnicze'
    match 'pracownicy/kalendarz' => 'workers#calendar' , :as => 'effectivenes_calendar'
    match 'efektywnosc/nowa' => 'effectivenes#create', :as => 'effectivenes_index'
    match 'tabela-normatywow' => 'tabelanormatywows#index', :as => 'tabela_normatywow'
    match 'tabela-transportowa' => 'tabelatransportowas#index', :as => 'tabela_transportowa'
    match 'typy-czynnosci' => 'typyczynnoscis#index', :as => 'typy_czynnosci'
    match 'tabela-czasow-dostepnych' => 'tabelaczasowdostepnychs#index', :as => 'tabela_czasow_dostepnych'
    match 'tabela-realizacji-norm' => 'realizacjanorms#index', :as => 'tabela_realizacji_norm'

    match 'obszar/edytuj/:id' => 'pomocniczes#edit_obszar', :as => 'edit_obszar'
    match 'obszar/update/:id' => 'pomocniczes#update_obszar', :as => 'obszar'
    match 'dodatek/edytuj/:id' => 'pomocniczes#edit_dodatek', :as => 'edit_dodatek'
    match 'dodatek/update/:id' => 'pomocniczes#update_dodatek', :as => 'dodatki'
    match 'predkosc/edytuj/:id' => 'pomocniczes#edit_predkosc', :as => 'edit_predkosc'
    match 'predkosc/update/:id' => 'pomocniczes#update_predkosc', :as => 'predkosci'

    match 'pracownik/usun/:id' => 'workers#delete', :as => 'usun_po_id'
    match 'typy-czynnosci/usun/:id' => 'typyczynnoscis#delete', :as => 'usun_po_id_czynnosc'
    match 'tabela-czynnosci/usun/:id' => 'tabelanormatywows#delete', :as => 'usun_po_id_normatyw'
    match 'tabela-transportowa/usun/:id' => 'tabelatransportowas#delete', :as => 'usun_po_id_transport'
    match 'tabela-czasow-dostepnych/usun/:id' => 'tabelaczasowdostepnychs#delete', :as => 'usun_po_id_czas_dostepny'
    match 'tabela-realizacji-norm/usun/:id' => 'realizacjanorms#delete', :as => 'usun_po_id_realizacja_norm'
    match 'pomocnicze/usun/:id' => 'pomocniczes#delete', :as => 'usun_po_id_predkosc'
    match 'pomocnicze/usun-dodatek/:id' => 'pomocniczes#delete_dodatek', :as => 'usun_po_id_dodatek'
    match 'pomocnicze/usun-obszar/:id' => 'pomocniczes#delete_obszar', :as => 'usun_po_id_obszar'
    match 'pracownik/:id2/cel/usun/:id' => 'celes#delete', :as => 'usun_po_id_cel'
    match 'pracownik/:id2/premia/usun/:id' => 'premies#delete', :as => 'usun_po_id_premia'
    match 'pracownik/:id2/efektywnosc/usun/:id' => 'effectivenes#delete', :as => 'usun_po_id_efektywnosc'
    match 'raporty/premie/usun/:id' => 'premies#delete', :as => 'usun_premia'
    match 'raporty/premie' => 'raporty#premie', :as => 'raport_premie'

    resources :typyczynnoscis do
      collection {get :index}
    end

    resources :searches
    resources :sessions
    resources :users
    resources :celes
    resources :premies
    resources :effectivenes
    resources :realizacjanorms
    resources :effectivene

    resources :tabelatransportowas

    
    match '/tabela-normatywow/export' => 'tabelanormatywow#export', :as => :export_normatywow
    match '/tabela-transportowa/export' => 'tabelatransportowas#export', :as => :export_tabela_transportowa
    match '/typy-czynnosci/export' => 'typyczynnosci#export', :as => :export_czynnosci
    match '/tabela-czasow-dostepnych/export' => 'tabelaczasowdostepnychs#export', :as => :export_czasy_dostepne
    match '/tabela-realizacji-norm/export' => 'realizacjanorms#export', :as => :export_realizacja_norm

    resources :workers do 
      collection {post :import , :import_tn, :import_tc, :import_tt,:import_tdc, :import_rn,:import_rn_finall,:import_workers,:import_stanowiska,:import_jednostki_organizacyjne}
    end

   match ':controller(/:action(/:id))(.:format)'
end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :keywords, :id_worker, :id_worker_merx, :min_effectivity, :max_effectivity, :date_from, :date_to, :name_tokens, :stanowisko, :obszar, :jedn_organizacyjna
  has_many :workers

def workers
  @workers ||= find_products
end

def name_tokens=(ids)
end

private

def find_products
  @array = keywords.split(",").map(&:to_i)
  if @array.size > 0  
     val = { :id => @array}
    else
     val = conditions
  end
  Worker.find(:all, :conditions => val, :include => [:effectivenes], :joins => ["left join realizacja_norm rn on rn.rn_id_worker_merx =  workers.id_worker_merx"]).uniq
end


def id_worker_conditions
  ["workers.id_worker in (?)", id_worker] unless id_worker.blank?
end
def keywords_conditions 

end
def id_worker_merx_conditions
  ["workers.id_worker_merx in (?)", id_worker_merx] unless id_worker_merx.blank?
end
def stanowisko_conditions
  ["workers.stanowisko = ?", stanowisko] unless stanowisko.blank?
end
def jedn_organizacyjna_conditions
  ["workers.jednostka_organizacyjna = ?", jedn_organizacyjna] unless jedn_organizacyjna.blank?
end
def jedn_organizacyjna_conditions
  ["workers.obszar = ?", obszar] unless obszar.blank?
end

def minimum_effectivity_conditions
  ["effectivenes.effectivity >= ?", min_effectivity] unless min_effectivity.blank?
end

def maximum_effectivity_conditions
  ["effectivenes.effectivity <= ?", max_effectivity] unless max_effectivity.blank?
end

def date_from_conditions
  ["rn.rn_data >= ?", date_from] unless date_from.blank?
end

def date_to_conditions
  ["rn.rn_data <= ?", date_to] unless date_to.blank?
end



def conditions
  [conditions_clauses.join(' AND '), *conditions_options]
end

def conditions_clauses
  conditions_parts.map { |condition| condition.first }
end

def conditions_options
  conditions_parts.map { |condition| condition[1..-1] }.flatten
end

def conditions_parts
  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    filter_access_to :all

  layout 'search'

  def index
    @searchess = Search.all
    @searches = Worker.where("last_name like ? or first_name like ?", "%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
    format.html
    format.json { render :json => @searches.map{|contact|
     {:id => contact.id, :name => contact.last_name + " " + contact.first_name }}}
  end
  end

  def show
    @search = Search.find(params[:id])
 

  end

  def new
    @search = Search.new
    @searches = Worker.where("last_name like ? or first_name like ?", "%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
    format.html
    format.json { render :json => @searches.map{|contact|
     {:id => contact.id, :name => contact.last_name + " " + contact.first_name }}}
  end
  end

  def create
    @search = Search.new(params[:search])
    if @search.save
      redirect_to szukaj_po_id_path(@search.id) , :notice => "Poprawnie przeprowadzono wyszukiwanie"
    else
      render :action => 'new'
    end
  end

  def edit
    @search = Search.find(params[:id])
  end

  def update
    @search = Search.find(params[:id])
    if @search.update_attributes(params[:search])
      redirect_to @search, :notice  => "Successfully updated search."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @search = Search.find(params[:id])
    @search.destroy
    redirect_to searches_url, :notice => "Successfully destroyed search."
  end

 def lista
    @search = Search.find(params[:id])
    respond_to do |format|
    format.html
    format.xls 
    end
  end


end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search do |f|  %>

  <p>
    <%= f.label "Imie, Nazwisko: " %><br />
    <%= f.text_field :keywords %>
  </p>
  <p>
    <%= f.label "Numer ID Pracownika: " %><br />
    <%= f.number_field :id_worker , :class=>"input-small"%>
  </p>
  <p>
    <%= f.label "Numer ID Pracownika MERX: " %><br />
    <%= f.number_field :id_worker_merx, :class=>"input-small" %>
  </p>
  <p>
    <%= f.label "Minimalna efektywność: " %><br />
    <%= f.number_field :min_effectivity, :class=>"input-small" %>
  </p><p>
    <%= f.label "Maksymalna efektywność: " %><br/>
    <%= f.number_field :max_effectivity , :class=>"input-small"%>
  </p>
  <p>
    <%= f.label "Od: " %><br />
    <%= f.text_field :date_from, :class=>"input-small"  %>
  </p>
  <p>
    <%= f.label "Do: " %><br />
    <%= f.text_field :date_to , :class=>"input-small"%>
  </p>
  <p><%= f.submit "Szukaj" , :class => "szukaj"%></p>
<% end %>

app/views/searches/_result-worker.html.erb
<div class="section list">
  <h1>Wyszukiwanie pracowników</h2>
<% title "Szczegóły pracownika" %>
<% 
     @tmp =[]
     @tabela_dat = []
     # @workers_id_table =[]
 data_table = GoogleVisualr::DataTable.new
  data_table.new_column('string', 'Dzień')
  data_table.new_column('number', 'Minimum')
  data_table.new_column('number', 'Maximum')
  j = 1
  @workers.each do |worker| 
  # @workers_id_table << worker.id
  @imie_nazwisko = imie_nazwisko_worker(worker.id)[0] +" "+ imie_nazwisko_worker(worker.id)[1]
  data_table.new_column('number', @imie_nazwisko.humanize )
    cmin = cel_min(worker.id)[0].to_f
    cmax = cel_max(worker.id)[0].to_f
    @effec = Realizacjanorm.find(:all, :conditions => ["rn_id_worker_merx in (?)" ,
                                               worker.id_worker_merx], :order => "rn_data asc") 
    @effec.each do |a|
  
     @narray = Array.new(@workers.size,0)
     @narray.insert(0,a.rn_data.strftime('%Y-%m-%d'),cmin,cmax)
     @narray.insert(j+2,(a.rn_normatywy_czas_suma_tg.to_f/100).round(2))
     @narray.delete_at(j+3) 
     @tabela_dat << [worker.id, a.rn_data.strftime('%Y-%m-%d')]
     @tmp <<  @narray

    end
   j = j + 1
  end

  @celes = []
  @tabela_dat.sort.uniq.each do |td|
      @celes << [td[1],cel_min_by_date(td[0],td[1])[0].to_f,cel_max_by_date(td[0],td[1])[0].to_f ]
  end
  @cele_tabela = @celes.group_by(&:first).map do |date, rs|
  values = rs[0].zip(*rs[1..-1]).drop(1).map { |xs| xs.reduce(:+)/rs.size }
  [values].flatten

  end
    @aggregated_rows = @tmp.group_by(&:first).map do |date, rs|
  values = rs[0].zip(*rs[1..-1]).drop(3).map { |xs| xs.reduce(:+)}

  [date, values].flatten
  end 
  i=0
  @aggregated_rows.each do |ar|
    ar.insert(1,@cele_tabela[i][0], @cele_tabela[i][1] )
    i+=1
  end
  data_table.add_rows(@aggregated_rows)
 
  opts   = { 
        :width => '100%', 
        :height => '100%', 
        :vAxis => {:title => 'Efektywność',
           viewWindowMode: 'explicit',
              viewWindow:{
                min:0
              }

          }, 
        :hAxis => {:title => 'Dzień'},
       
        :chartArea => { :left => 50,  
                        :top => 50,
                        :width => 800,
                        :height => 350
                        }, 
        :seriesType => 'bars', 
        :bar => {groupWidth: 80},

        :series => {
          '1' => {:type => 'line'}, 
          '0' => {:type => 'line'}
          } 

        }
  @chart = GoogleVisualr::Interactive::ComboChart.new(data_table, opts)

  %>

  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    
  



<div id='chart' class="chart"></div>
<%= render_chart @chart, 'chart' %>


<h1>Szczegółowe informacje:</h1>   
<%= button_to "" ,raport_pracownicy_efektywnosc_path(format: "xls"), :class => "export-excel" %>


<table class="result-search" cellspacing="" summary="Section list">
  <tr class="header">
      <th>ID </th>
      <th>ID Merx </th>
      <th>Nazwisko</th>
      <th>Imie</th>
      <th>Najlepsza Efektywność</th>
      <th>Najgorsza Efektywność</th>
      <th>Realizacja Celu</th>
    </tr>
    <% @@lista_id = [] %>

 <% @workers.each do |worker| %>
 <tr>
 
   <td><%= worker.id_worker %></td>
   <% @@lista_id << worker.id %>
   
      <td><%= worker.id_worker_merx %></td>
      <td style="width:150px;"><%= worker.last_name %></td>
      <td style="width:150px;"><%= worker.first_name %></td>
      <td style="text-align:right"><%= maximum_effectivity(worker.id) %>%</td>
      <td style="text-align:right"><%= minimum_effectivity(worker.id) %>%</td>
      <% 
      val1 = minimum_effectivity(worker.id)
      val2 = cel_min(worker.id)[0].to_f
      val3 = cel_max(worker.id)[0].to_f
     
          if val2 == 0 and val3 == 0
            val4 = 0
          else
            val4 = (((val1-val2)/(val3-val2))*100).round
          end

        if val4 < 0
          @klasa = "bad"
        else
          @klasa = "ok"
        end

       %>
      <td class="<%= @klasa %>" style="text-align:right;"><%= val4 %>%</td>
      
   
   
     
     
    
     
    
      </td>
      <td><%= button_to("", szczegoly_po_id_path(worker.id), :class=>"details", :title=>"Szczegóły pracownika #{worker.last_name.humanize} #{worker.first_name.humanize}" ) %></td>



      </tr>
          
     <% end %>
   </table>
<br>

app/views/searches/edit.html.erb
<% title = "Edit Search" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @search %> |
  <%= link_to "View All", searches_path %>
</p>

app/views/searches/index.html.erb
<% title = "Searches" %>

<table>
  <tr>
    <th>Keywords</th>
    <th>Id Worker</th>
    <th>Id Worker Merx</th>
    <th>Min Effectivity</th>
    <th>Max Effectivity</th>
    <th>Date From</th>
    <th>Date To</th>
  </tr>
  <% for search in @searches %>
    <tr>
      <td><%= search.keywords %></td>
      <td><%= search.id_worker %></td>
      <td><%= search.id_worker_merx %></td>
      <td><%= search.min_effectivity %></td>
      <td><%= search.max_effectivity %></td>
      <td><%= search.date_from %></td>
      <td><%= search.date_to %></td>
      <td><%= link_to "Show", search %></td>
      <td><%= link_to "Edit", edit_search_path(search) %></td>
      <td><%= link_to "Destroy", search, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Search", new_search_path %></p>

app/views/searches/lista.xls.erb
<% data = DateTime.now.to_date.strftime("%d-%m-%Y") %>
<% headers["Content-Disposition"] = "attachment; filename=\"lista-pracownikow-i-efektywnosci-#{data}.xls\""  %>
<% @workers = @search.workers %>
<table class="listing" summary="Section list">
  <tr class="header">
      <th>ID<br/>Pracownika</th>
      <th>ID<br/>Merx<br/>Pracownika</th>
      <th>Nazwisko</th>
      <th>Imie</th>
      <th>Najlepsza<br/>Efektywność</th>
      <th>Najgorsza<br/>Efektywność</th>
      <th>Realizacja<br/>Celu</th>
    </tr>
    <% @@lista_id = [] %>

 <% @workers.each do |worker| %>
 <tr>
 
   <td><%= worker.id_worker %></td>
   <% @@lista_id << worker.id %>
   
      <td><%= worker.id_worker_merx %></td>
      <td><%= worker.last_name %></td>
      <td><%= worker.first_name %></td>
      <td style="text-align:right"><%= maximum_effectivity(worker.id) %>%</td>
      <td style="text-align:right"><%= minimum_effectivity(worker.id) %>%</td>
      <% 
      val1 = minimum_effectivity(worker.id)
      val2 = cel_min(worker.id)[0].to_f
      val3 = cel_max(worker.id)[0].to_f
     
          if val2 == 0 and val3 == 0
            val4 = 0
          else
            val4 = (((val1-val2)/(val3-val2))*100).round
          end

        if val4 < 0
          @klasa = "bad"
        else
          @klasa = "ok"
        end

       %>
      <td class="<%= @klasa %>" style="text-align:right;"><%= val4 %>%</td>
      
      </td>


      </tr>
          
     <% end %>
   </table>
<br>

app/views/searches/new.html.erb
<% title "Raport pracownika" %>


<div id="header" class="header-colored" style="background-color:rgb(233, 135, 29); ">
Generowanie raportu
</div>
<a href="#" id="hide" style="float:right; margin-top:-22px; color:#fff; font-weight:500; text-decoration:none;" ><span>-</span></a><div id="visable-div" >
<div id ="left" style="float:left; width:50%">
  
<%= form_for @search do |f|  %>

  <table cellpadding="5" style="float:left;">
  	<tbody>
  		<tr>
  			<td style="width:100px;"><%= f.label "Imie, Nazwisko: " %></td>
	  		<td colspan="3"><%= f.text_field :keywords , :class=>"input-search big" %></td>
	  		
			
  		</tr>
  		<tr >
  			<td ><%= f.label "ID Pracownika: " %> </td>
			<td style="width:50px;"> <%= f.text_field :id_worker , :class=>"input-search small"%></td>
			<td><%= f.label "ID MERX Pracownika: " %></td>
			<td><%= f.text_field :id_worker_merx, :class=>"input-search small" %></td>
  		</tr>
  		<tr>
  			<td style="width:50px;"><%= f.label "Minimalna efektywność: " %></td>
  			<td style="width:50px;"><%= f.number_field :min_effectivity, :class=>"input-search small" %></td>
  		  <td style="width:50px;"><%= f.label "Maksymalna efektywność: " %></td>
        <td><%= f.number_field :max_effectivity , :class=>"input-search small"%></td>
	       <tr>
         <td style="width:50px;"><%= f.label "Stanowisko: " %></td>
    <td><%= f.collection_select  :stanowisko, Position.order("name asc") , :name, :name, :include_blank => true %></td>
    <td style="width:50px;"><%= f.label "Jednostka organizacyjna: " %></td>
    <td><%= f.collection_select  :jedn_organizacyjna, Jednostkaorganizacyjna.order("name asc") , :name, :name, :include_blank => true %></td>
    </tr>
    <tr>
             <td style="width:50px;"><%= f.label "Obszar: " %></td>

    <td><%= f.collection_select  :obszar, Obszar.order("ob_kod asc") , :ob_kod,  :pelna_nazwa_obszaru , :include_blank => true %></td>
    </tr>

  		</tr>
  	</tbody>
  </table>
   

</div>
   <div id="right" style="float:right; width:38%; padding-left:100px;">
     
 
   
   <table id="table-for-calendar" >
    		<tr>
    				<td class="new_search"><%= f.label "Data od: " %></td>
    				<td class="new_search"><%= f.label "Data do: " %></td>
    			</tr>
    		<tr >
    			<td ><div id="date_from_div"></div></td>
    			<td ><div id="date_to_div"></div></td>
    		</tr>
    		<tr>
    			<td>    <%= f.text_field :date_from, :class=>"input-search middle "  %></td>
    			<td>    <%= f.text_field :date_to , :class=>"input-search middle"%></td>
    		</tr>
    		<tr>

    		</tr>
    			

    </table> 
<div id="timestamp" style="float:right">
	
    <input type="radio" id="kwartal" name="radio" /><label for="kwartal">Kwartał</label>
    <input type="radio" id="miesiac" name="radio" /><label for="miesiac">Miesiąc</label>
    <input type="radio" id="tydzien" name="radio" checked="checked" /><label for="tydzien">Tydzień</label>
  </div>

 

 
   </div>

  <%= f.submit "" , :class => "szukaj"%>
<% end %>
</diV>

app/views/searches/show.html.erb
<% title = "Search" %>

<% @workers = @search.workers %>
<%= render :partial => 'wyniki-wyszukiwania' %>